Repository nimblehq/ios-templates, pull requests merged in 2018-04, with the labels that each got.

#17 Integrate SwiftLint
  __PROJECT NAME__/.swiftlint.yml
  __PROJECT NAME__/Podfile
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
Labels: type : feature

#26 Setup Template with Code Signing
  README.md
  __PROJECT NAME__/.gitignore
  __PROJECT NAME__/Gemfile
  __PROJECT NAME__/Gemfile.lock
  __PROJECT NAME__/fastlane/.env
  __PROJECT NAME__/fastlane/Appfile
  __PROJECT NAME__/fastlane/Fastfile
  __PROJECT NAME__/fastlane/Gymfile
Labels: priority : normal, type : feature

#29 Fastlane Upload to crashlytics
  README.md
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
  __PROJECT NAME__/fastlane/.env
  __PROJECT NAME__/fastlane/Crashlytics/Crashfile
  __PROJECT NAME__/fastlane/Developer Portal/Codefile
  __PROJECT NAME__/fastlane/Fastfile
  __PROJECT NAME__/fastlane/iTunesConnect/Connectfile
  __PROJECT NAME__/release_notes.txt
Labels: priority : normal, type : feature

#21 Set Export dSYM for all Target
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
Labels: priority : normal

#31 remove scheme build condition.
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
Labels: priority : normal, type : chore

#33 ensure remove - from app name
  __PROJECT NAME__/fastlane/Developer Portal/Codefile
Labels: priority : normal, type : bug

#34 Configure SwiftLint rules
  __PROJECT NAME__/.swiftlint.yml
Labels: priority : normal, type : chore
