Repository nimblehq/ios-templates, pull requests merged in 2018-03, with the labels that each got.

#1 Init Xcode project with Cocoapods integrated
  .gitignore
  __PROJECTNAME__/Podfile
  __PROJECTNAME__/Podfile.lock
  __PROJECTNAME__/__PROJECTNAME__.xcodeproj/project.pbxproj
  __PROJECTNAME__/__PROJECTNAME__.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  __PROJECTNAME__/__PROJECTNAME__.xcworkspace/contents.xcworkspacedata
  __PROJECTNAME__/__PROJECTNAME__/AppDelegate.swift
  __PROJECTNAME__/__PROJECTNAME__/Assets.xcassets/AppIcon.appiconset/Contents.json
  __PROJECTNAME__/__PROJECTNAME__/Base.lproj/LaunchScreen.storyboard
  __PROJECTNAME__/__PROJECTNAME__/Base.lproj/Main.storyboard
  __PROJECTNAME__/__PROJECTNAME__/Info.plist
  __PROJECTNAME__/__PROJECTNAME__/ViewController.swift
  __PROJECTNAME__/__PROJECTNAME__/__PROJECTNAME__ staging-Info.plist
  __PROJECTNAME__/__PROJECTNAME__Tests/Info.plist
  __PROJECTNAME__/__PROJECTNAME__Tests/__PROJECTNAME__Tests.swift
  __PROJECTNAME__/__PROJECTNAME__UITests/Info.plist
  __PROJECTNAME__/__PROJECTNAME__UITests/__PROJECTNAME__UITests.swift
  xcrecipe.json
Labels: priority : high, type : feature

#13 include shared schemes to the template
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/xcshareddata/xcschemes/__PROJECT NAME__ debug.xcscheme
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/xcshareddata/xcschemes/__PROJECT NAME__ staging.xcscheme
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/xcshareddata/xcschemes/__PROJECT NAME__.xcscheme
Labels: priority : normal, type : feature

#16 define product name / bundle_id for each scheme
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
Labels: type : bug

#23 Change codesiging to Manual
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
Labels: priority : normal

#24 update README
  README.md
Labels: priority : normal, type : chore

#25 Change Info.plist to relative path
  __PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
Labels: priority : normal
