Repository nimblehq/ios-templates, pull requests merged in 2020-12, with the labels that each got.

#121 Release version 2.0.0
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  LICENSE
  Nimble Templates/App.xctemplate/TemplateIcon.png
  Nimble Templates/App.xctemplate/TemplateIcon@2x.png
  Nimble Templates/App.xctemplate/TemplateInfo.plist
  Nimble Templates/App.xctemplate/___PACKAGENAME___ Staging.xcscheme
  Nimble Templates/App.xctemplate/___PACKAGENAME___ UAT.xcscheme
  Nimble Templates/App.xctemplate/___PACKAGENAME___.xcscheme
  Nimble Templates/Cocoa Touch App Base.xctemplate/Assets.xcassets/AccentColor.colorset/Contents.json
  Nimble Templates/Cocoa Touch App Base.xctemplate/Assets.xcassets/Contents.json
  Nimble Templates/Cocoa Touch App Base.xctemplate/LaunchScreen.storyboard
  Nimble Templates/Cocoa Touch App Base.xctemplate/TemplateInfo.plist
  README.md
  images/project-config/default-build-configurations.png
  images/project-config/default-configurations.png
  images/project-config/default-custom-flags.png
  images/project-config/default-dsym.png
  images/readme/configuration_custom-attributes.png
  images/readme/configuration_default-attributes.png
  images/readme/configuration_result.png
  images/readme/configurations_remove-default-configurations.png
  images/readme/scheme_add-targets-uuid-to-blueprint-identifier.png
  images/readme/scheme_remove-folder.png
  images/readme/scheme_result.png
  images/readme/scheme_targets-auto-generated-uuid.png
  install.sh
Labels: priority : normal

#123 [100] Add Podfile - Configure Bundle gems: Cocoapods
  Nimble Templates/App.xctemplate/Podfile
  Nimble Templates/App.xctemplate/TemplateInfo.plist
Labels: type : feature

#125 [124] Configured bundle identifiers not set to bundle identifiers of newly created project.
  Nimble Templates/App Base.xctemplate/TemplateInfo.plist
  Nimble Templates/App.xctemplate/TemplateInfo.plist
  Nimble Templates/Bundle Base.xctemplate/TemplateInfo.plist
  Nimble Templates/Cocoa Touch App Base.xctemplate/TemplateInfo.plist
Labels: type : bug

#126 [119] Fix SceneDelegate.swift is not initialized correctly after creating a new project with SwitfUI
  Nimble Templates/App.xctemplate/TemplateInfo.plist
Labels: type : bug

#127 [122] Replace old configurations with XCConfig files
  Nimble Templates/App Base.xctemplate/TemplateInfo.plist
  Nimble Templates/App.xctemplate/TemplateInfo.plist
  Nimble Templates/Bundle Base.xctemplate/TemplateInfo.plist
  Nimble Templates/Cocoa Touch App Base.xctemplate/TemplateInfo.plist
Labels: type : feature
