Repository nimblehq/ios-templates, pull requests merged in 2021-08, with the labels that each got.

#141 [140] Add UITest template and update install script
  UITest Templates/UITestProtocols.xctemplate/AccessibilityIdentifiable.swift
  UITest Templates/UITestProtocols.xctemplate/AccessibilityIdentifiers.swift
  UITest Templates/UITestProtocols.xctemplate/IdentifierProvidable.swift
  UITest Templates/UITestProtocols.xctemplate/Screen.swift
  UITest Templates/UITestProtocols.xctemplate/ScreenProtocol.swift
  UITest Templates/UITestProtocols.xctemplate/TemplateIcon.png
  UITest Templates/UITestProtocols.xctemplate/TemplateIcon@2x.png
  UITest Templates/UITestProtocols.xctemplate/TemplateInfo.plist
  UITest Templates/UITestSpec.xctemplate/TemplateIcon.png
  UITest Templates/UITestSpec.xctemplate/TemplateIcon@2x.png
  UITest Templates/UITestSpec.xctemplate/TemplateInfo.plist
  UITest Templates/UITestSpec.xctemplate/___VARIABLE_moduleName___FlowSpec.swift
  UITest Templates/UITestSpec.xctemplate/___VARIABLE_moduleName___Identifier.swift
  UITest Templates/UITestSpec.xctemplate/___VARIABLE_moduleName___Screen.swift
  install.sh
Labels: type : feature

#162 Add the Github release PR template
  .github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
Labels: type : feature, @3.0.0

#163 [#143] Move Github Action workflows to .github/workflows
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  .github/workflows/test.yml
Labels: type : feature, @3.0.0

#159 [#151] Move tools, xcode-templates and its scripts out of the repository
  README.md
  UITest Templates/UITestProtocols.xctemplate/AccessibilityIdentifiable.swift
  UITest Templates/UITestProtocols.xctemplate/AccessibilityIdentifiers.swift
  UITest Templates/UITestProtocols.xctemplate/IdentifierProvidable.swift
  UITest Templates/UITestProtocols.xctemplate/Screen.swift
  UITest Templates/UITestProtocols.xctemplate/ScreenProtocol.swift
  UITest Templates/UITestProtocols.xctemplate/TemplateIcon.png
  UITest Templates/UITestProtocols.xctemplate/TemplateIcon@2x.png
  UITest Templates/UITestProtocols.xctemplate/TemplateInfo.plist
  UITest Templates/UITestSpec.xctemplate/TemplateIcon.png
  UITest Templates/UITestSpec.xctemplate/TemplateIcon@2x.png
  UITest Templates/UITestSpec.xctemplate/TemplateInfo.plist
  UITest Templates/UITestSpec.xctemplate/___VARIABLE_moduleName___FlowSpec.swift
  UITest Templates/UITestSpec.xctemplate/___VARIABLE_moduleName___Identifier.swift
  UITest Templates/UITestSpec.xctemplate/___VARIABLE_moduleName___Screen.swift
  install.sh
  resources/git-hooks/pre-push
  resources/images/project-config/default-build-configurations.png
  resources/images/project-config/default-configurations.png
  resources/images/project-config/default-custom-flags.png
  resources/images/project-config/default-dsym.png
  resources/images/readme/configuration_custom-attributes.png
  resources/images/readme/configuration_default-attributes.png
  resources/images/readme/configuration_result.png
  resources/images/readme/configurations_remove-default-configurations.png
  resources/images/readme/scheme_add-targets-uuid-to-blueprint-identifier.png
  resources/images/readme/scheme_remove-folder.png
  resources/images/readme/scheme_result.png
  resources/images/readme/scheme_targets-auto-generated-uuid.png
  resources/xcode-code-snippets/unit-test/unit-test-context.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-interactor-it-trigger.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-it.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-presenter-it-call.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-router-it-present.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-router-itpush.codesnippet
  resources/xcode-code-snippets/unit-test/unit-test-swiftlint-headline-disable.codesnippet
  resources/xcode-templates/App.xctemplate/Gemfile
  resources/xcode-templates/App.xctemplate/Podfile
  resources/xcode-templates/App.xctemplate/TemplateIcon.png
  resources/xcode-templates/App.xctemplate/TemplateIcon@2x.png
  resources/xcode-templates/App.xctemplate/TemplateInfo.plist
  resources/xcode-templates/App.xctemplate/___PACKAGENAME___ Staging.xcscheme
  resources/xcode-templates/App.xctemplate/___PACKAGENAME___ UAT.xcscheme
  resources/xcode-templates/App.xctemplate/___PACKAGENAME___.xcscheme
  resources/xcode-templates/App.xctemplate/fastlane/Constants/Constants.rb
  resources/xcode-templates/App.xctemplate/fastlane/Fastfile
  resources/xcode-templates/App.xctemplate/fastlane/Managers/CodeSigningManager.rb
  resources/xcode-templates/App.xctemplate/fastlane/Managers/TestManager.rb
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/Assets.xcassets/AccentColor.colorset/Contents.json
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/Assets.xcassets/Contents.json
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/LaunchScreen.storyboard
  resources/xcode-templates/Cocoa Touch App Base.xctemplate/TemplateInfo.plist
  scripts/colors.sh
  scripts/helpers.sh
Labels: type : chore, @3.0.0

#169 [166] Generating the project: Configurations and Resources
  Project.swift
  ProjectName/Configurations/Plists/Info.plist
  ProjectName/Configurations/XCConfigs/Debug.xcconfig
  ProjectName/Configurations/XCConfigs/Release.xcconfig
  ProjectName/Resources/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  ProjectName/Resources/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  ProjectName/Resources/Assets/Assets.xcassets/Contents.json
  ProjectName/Resources/LaunchScreen/LaunchScreen.storyboard
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
Labels: type : feature, @3.0.0, epic : tuist

#172 [166] Generating the project: Constants and Supports
  ProjectName/Sources/Constants/Constants+API.swift
  ProjectName/Sources/Constants/Constants.swift
  ProjectName/Sources/Supports/Extensions/Foundation/Optional+Unwrap.swift
  ProjectName/Sources/Supports/Extensions/UIKit/Color+Application.swift
  ProjectName/Sources/Supports/Extensions/UIKit/UIView+Subviews.swift
  ProjectName/Sources/Supports/Helpers/Typealiases/Typealiases.swift
Labels: type : feature

#175 [173] Setup shell script Build Phase for libraries
  .sourcery.yml
  .swiftlint.yml
  Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
  Tuist/ProjectDescriptionHelpers/TargetAction+Initializing.swift
  tools/sourcery/templates/AutoMockable.stencil
Labels: type : feature, @3.0.0

#174 [165] setup build configuration
  Project.swift
  ProjectName/Configurations/XCConfigs/Debug.xcconfig
  ProjectName/Configurations/XCConfigs/DebugProduction.xcconfig
  ProjectName/Configurations/XCConfigs/DebugStaging.xcconfig
  ProjectName/Configurations/XCConfigs/Release.xcconfig
  ProjectName/Configurations/XCConfigs/ReleaseProduction.xcconfig
  ProjectName/Configurations/XCConfigs/ReleaseStaging.xcconfig
  Tuist/ProjectDescriptionHelpers/ProjectBuildConfiguration.swift
Labels: type : feature, @3.0.0, epic : tuist

#145 [101] Template for bitrise
  README.md
  bitrise.yml
  resources/images/CICD/bitrise-file-location.png
Labels: type : feature
