Repository nimblehq/ios-templates, pull requests merged in 2021-11, with the labels that each got.

#222 [#221] Include ignore SwiftLint file_name for extensions Files.
  {PROJECT_NAME}/Sources/Constants/Constants+API.swift
  {PROJECT_NAME}/Sources/Supports/Extensions/UIKit/Color+Application.swift
  {PROJECT_NAME}/Sources/Supports/Helpers/Typealiases/Typealiases.swift
Labels: type : feature, @3.2.0

#223 [#220] Pull Request review Workflow seems to be failing
  fastlane/Fastfile
  fastlane/Managers/TestManager.rb
Labels: type : bug, @3.2.0

#224 [#219] Add wiki content into repository
  .github/workflows/publish_docs_to_wiki.yml
  docs/Home.md
  docs/_Footer.md
  docs/_Sidebar.md
Labels: type : feature, @3.2.0

#232 [#209] Clear all warnings on fresh generated project
  .swift-version
  .swiftformat
  Podfile
  Tuist/ProjectDescriptionHelpers/TargetAction+Initializing.swift
  {PROJECT_NAME}/Sources/Constants/Constants+API.swift
  {PROJECT_NAME}/Sources/Constants/Constants.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/NetworkAPI.swift
  {PROJECT_NAME}/Sources/Domain/UseCases/UseCaseFactoryProtocol.swift
  {PROJECT_NAME}/Sources/Presentation/Navigator/Navigator+Scene.swift
  {PROJECT_NAME}/Sources/Presentation/Navigator/Navigator.swift
Labels: type : chore

#233 [#208] Fix: R.generated.swift need to be created to include into project
  .swiftlint.yml
  Tuist/ProjectDescriptionHelpers/TargetAction+Initializing.swift
  make.sh
Labels: type : bug

#234 Release - 3.2.0
  .github/workflows/publish_docs_to_wiki.yml
  .swift-version
  .swiftformat
  .swiftlint.yml
  Podfile
  Tuist/ProjectDescriptionHelpers/TargetAction+Initializing.swift
  docs/Home.md
  docs/_Footer.md
  docs/_Sidebar.md
  fastlane/Fastfile
  fastlane/Managers/TestManager.rb
  make.sh
  {PROJECT_NAME}/Sources/Constants/Constants+API.swift
  {PROJECT_NAME}/Sources/Constants/Constants.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/NetworkAPI.swift
  {PROJECT_NAME}/Sources/Domain/UseCases/UseCaseFactoryProtocol.swift
  {PROJECT_NAME}/Sources/Presentation/Navigator/Navigator+Scene.swift
  {PROJECT_NAME}/Sources/Presentation/Navigator/Navigator.swift
  {PROJECT_NAME}/Sources/Supports/Extensions/UIKit/Color+Application.swift
  {PROJECT_NAME}/Sources/Supports/Helpers/Typealiases/Typealiases.swift
Labels: type : release, @3.2.0
