Repository nimblehq/ios-templates, pull requests merged in 2021-09, with the labels that each got.

#180 [179] Incorrect build configuration setup
  Tuist/ProjectDescriptionHelpers/ProjectBuildConfiguration.swift
  Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift
Labels: type : bug, @3.0.0, epic : tuist

#157 [156] Update Fastlane for CICD
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  fastlane/Constants/Constants.rb
  fastlane/Constants/Environments.rb
  fastlane/Fastfile
  fastlane/Gymfile
  fastlane/Managers/BuildManager.rb
  fastlane/Managers/DistributionManager.rb
  fastlane/Managers/MatchManager.rb
  fastlane/Managers/SymbolManager.rb
  fastlane/Managers/VersioningManager.rb
  fastlane/Matchfile
  fastlane/Pluginfile
Labels: type : feature, @3.0.0

#170 [154] Add Fastlane
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  .github/workflows/test.yml
  Gemfile
  fastlane/Constants/Constants.rb
  fastlane/Fastfile
  fastlane/Managers/TestManager.rb
Labels: type : feature, @3.0.0

#171 [155] Add Cocoapods
  Gemfile
  Podfile
Labels: type : feature, @3.0.0

#177 [166] Generating: Source folder
  ProjectName/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  ProjectName/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  ProjectName/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  ProjectName/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  ProjectName/Sources/Data/NetworkAPI/Models/.gitkeep
  ProjectName/Sources/Data/NetworkAPI/NetworkAPI.swift
  ProjectName/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  ProjectName/Sources/Data/Repositories/.gitkeep
  ProjectName/Sources/Domain/Entities/.gitkeep
  ProjectName/Sources/Domain/Interfaces/.gitkeep
  ProjectName/Sources/Domain/UseCases/UseCaseFactoryProtocol.swift
  ProjectName/Sources/Presentation/Navigator/Navigator+Scene.swift
  ProjectName/Sources/Presentation/Navigator/Navigator+Transition.swift
  ProjectName/Sources/Presentation/Navigator/Navigator.swift
  ProjectName/Sources/Presentation/Views/.gitkeep
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
Labels: @3.0.0, epic : tuist

#188 [184] Remove unnecessary files
  resources/images/CICD/bitrise-file-location.png
Labels: type : bug, @3.0.0

#187 [166] Generating: Test and UITest target
  .gitignore
  ProjectNameTests/Configurations/Plists/Info.plist
  ProjectNameTests/Resources/.gitkeep
  ProjectNameTests/Sources/Dummy/.gitkeep
  ProjectNameTests/Sources/Specs/.gitkeep
  ProjectNameTests/Sources/Utilities/.gitkeep
  ProjectNameTests/UnitTests.swift
  ProjectNameUITests/Configurations/Plists/Info.plist
  ProjectNameUITests/Resources/.gitkeep
  ProjectNameUITests/Sources/.gitkeep
  ProjectNameUITests/UITests.swift
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
Labels: type : feature, epic : tuist

#190 [#189] [Chore] Fix swiftlint errors in DerivedData breaks Fastlane
  .swiftlint.yml
Labels: type : chore
