Repository nimblehq/ios-templates, pull requests merged in 2022-03, with the labels that each got.

#246 [#226] Add Standard File Organization document
  docs/Standard-File-Organization.md
  docs/_Sidebar.md
Labels: priority : high

#251 [250] [Bug] Fix: Only update development profiles when registering a new device
  fastlane/Fastfile
  fastlane/Managers/MatchManager.rb
Labels: type : bug

#252 [244] [Feature] Add a workflow to publish documentation to Github Wiki
  .github/wiki/Automating-Wiki.md
  .github/wiki/Home.md
  .github/wiki/Standard-File-Organization.md
  .github/wiki/_Footer.md
  .github/wiki/_Sidebar.md
  .github/workflows/publish_docs_to_wiki.yml
Labels: @3.5.0
