Repository nimblehq/ios-templates, pull requests merged in 2022-04, with the labels that each got.

#257 Add the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore

#264 Update the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore, @3.6.0

#265 Update the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore, @3.6.0

#256 [#254] Show warnings for long compile code
  {PROJECT_NAME}/Configurations/XCConfigs/DebugProduction.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/DebugStaging.xcconfig
Labels: type : feature, @3.6.0

#263 [#259] Update Bitrise workflow to use Fastlane
  bitrise.yml
Labels: priority : normal, type : chore, @3.6.0
