Repository nimblehq/ios-templates, pull requests merged in 2022-05, with the labels that each got.

#267 Release - 3.6.0
  bitrise.yml
  {PROJECT_NAME}/Configurations/XCConfigs/DebugProduction.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/DebugStaging.xcconfig
Labels: type : release, @3.6.0

#273 [#269] Fix: Version of Sourcery
  Podfile
Labels: priority : high, type : bug, @3.7.0

#266 [#255] Update Tuist version - 3.x
  .tuist-version
  Project.swift
  Tuist/Config.swift
  Workspace.swift
Labels: type : feature, epic : tuist, @3.6.0

#274 [Chore] Add David and Taher into the Codeowners list
  .github/CODEOWNERS
Labels: type : chore, @3.7.0

#271 [#228] Add Project Dependencies document
  .github/wiki/Project-Dependencies.md
  .github/wiki/_Sidebar.md
Labels: type : content, @3.7.0

#278 [#231] Add Getting Started document
  .github/wiki/Automating-Wiki.md
  .github/wiki/Getting-Started.md
  .github/wiki/Home.md
  .github/wiki/_Sidebar.md
  README.md
Labels: type : content, @3.7.0

#268 [#227] Add Project Configurations document
  .github/wiki/Project-Configurations.md
  .github/wiki/Standard-File-Organization.md
  .github/wiki/_Sidebar.md
Labels: type : content, @3.7.0

#280 [#229] Add Github Actions Templates document
  .github/wiki/Github-Actions.md
  .github/wiki/_Sidebar.md
Labels: type : content, @3.7.0

#281 [#277] Update .swiftformat with --extensionacl on-declarations
  .swiftformat
Labels: type : chore
