Repository nimblehq/ios-templates, pull requests merged in 2022-08, with the labels that each got.

#314 [#312] Run `xcode_summary` on changed files only in Danger
  Dangerfile
Labels: priority : normal, type : feature

#313 [#270] [Bug] Fix: Errors occurred in Xcode and Sourcetree when run install script of ios-template
  make.sh
Labels: type : bug

#317 Add `workflow_dispatch` to manually trigger deploy workflows
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
Labels: type : chore

#318 [#289] Apple will remove bitcode in Xcode 14, we should remove bitcode from our configurations
  .github/wiki/Project-Configurations.md
  Podfile
  {PROJECT_NAME}/Configurations/XCConfigs/ReleaseProduction.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/ReleaseStaging.xcconfig
Labels: type : feature

#320 [#248][#319] Improve the infrastructure setup for iOS Projects, tuist generate from make.sh should not open Xcode automatically
  .github/wiki/Deliverable-Configurations.md
  .github/wiki/_Sidebar.md
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
  deliverable_setup.sh
  fastlane/Constants/Constants.rb
  fastlane/Constants/DeliverableConstants.rb
  fastlane/Fastfile
  make.sh
Labels: type : feature

#323 [#322] Add Multiline Parameter Lint
  .swiftformat
  .swiftlint.yml
Labels: type : feature

#326 [#301] [Fix] Constants.DEV_PORTAL_APPLE_ID is unused by mistake
  fastlane/Fastfile
  fastlane/Managers/MatchManager.rb
Labels: type : bug

#331 Release - 3.9.0
  .github/CODEOWNERS
  .github/wiki/Deliverable-Configurations.md
  .github/wiki/Project-Configurations.md
  .github/wiki/_Sidebar.md
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  .swiftformat
  .swiftlint.yml
  Dangerfile
  Podfile
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
  deliverable_setup.sh
  fastlane/Constants/Constants.rb
  fastlane/Constants/DeliverableConstants.rb
  fastlane/Fastfile
  fastlane/Managers/MatchManager.rb
  make.sh
  {PROJECT_NAME}/Configurations/XCConfigs/ReleaseProduction.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/ReleaseStaging.xcconfig
Labels: type : release
