Repository nimblehq/ios-templates, pull requests merged in 2022-11, with the labels that each got.

#371 Release - 3.11.0
  README.md
Labels: type : release

#370 [#351] Add steps in CI/CD templates to support upload builds and dSYM files to build artifacts of CI/CD platforms (Github Actions, Bitrise)
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  bitrise.yml
  fastlane/Constants/Environments.rb
  fastlane/Fastfile
  fastlane/Managers/EnvironmentManager.rb
Labels: type : feature

#381 [Chore] Update Project for Xcode 14
  .github/workflows/test_upload_build_to_test_flight.yml
  Podfile
  fastlane/Fastfile
  fastlane/Managers/BuildManager.rb
Labels: type : chore, type : feature

#384 [#382] [Fastlane Swift] Support uploading build and dSYM files to build artifacts of CI/CD platforms
  fastlane/Constants/Constant.swift
  fastlane/Constants/Secret.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Build.swift
  fastlane/Helpers/EnvironmentParser.swift
  fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj
Labels: type : feature

#391 [#387] Fastlane Swift - Fix Xcode Grouping causes FastlaneRunner to fail to generate
  fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj
Labels: type : chore

#393 [#373] Add a workflow to automatically draft a release
  .github/release-drafter.yml
  .github/workflows/draft-a-new-release.yml
Labels: type : feature

#396 Release - 3.12.0
  .github/release-drafter.yml
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  .github/workflows/draft-a-new-release.yml
  .github/workflows/test_upload_build_to_test_flight.yml
  Podfile
  Project.swift
  bitrise.yml
  fastlane/Constants/Environments.rb
  fastlane/Fastfile
  fastlane/Managers/BuildManager.rb
  fastlane/Managers/EnvironmentManager.rb
Labels: type : release
