Repository nimblehq/ios-templates, pull requests merged in 2022-06, with the labels that each got.

#285 Release - 3.7.0
  .github/CODEOWNERS
  .github/wiki/Automating-Wiki.md
  .github/wiki/Bitrise.md
  .github/wiki/Getting-Started.md
  .github/wiki/Github-Actions.md
  .github/wiki/Home.md
  .github/wiki/Project-Configurations.md
  .github/wiki/Project-Dependencies.md
  .github/wiki/Standard-File-Organization.md
  .github/wiki/_Sidebar.md
  .github/wiki/assets/images/bitrise/Bitrise-YML-Storage-Location.png
  .swiftformat
  .tuist-version
  Podfile
  Project.swift
  README.md
  Tuist/Config.swift
  Workspace.swift
  make.sh
Labels: type : release, @3.7.0

#287 [#284] Add trigger when `main` branch is updated
  .github/wiki/Bitrise.md
  bitrise.yml
Labels: type : chore

#295 [#293] [Bug] Fix: There is no lane name run_xcov in Fastfile
  .github/wiki/Bitrise.md
  bitrise.yml
Labels: type : bug

#297 [#296] [Bug] Fix: Add step to clean up previous code coverage report into bitrise.yml
  .github/wiki/Bitrise.md
  bitrise.yml
Labels: type : bug, type : chore, type : content

#294 [#291] [Chore] Create Github Wiki document to introduce Fastlane set up in this template
  .github/wiki/Fastlane.md
  .github/wiki/_Sidebar.md
  .github/wiki/assets/images/infrastructure/fastlane/fastlane.png
Labels: type : chore, type : content

#299 [#286] [Bug] Fix: The trigger setup for the publish docs to wiki workflow
  .github/workflows/publish_docs_to_wiki.yml
Labels: type : bug

#298 [#279] [Chore] Improve Project Configuration content
  .github/wiki/Project-Configurations.md
Labels: type : chore, type : content

#300 [#290] [Chore] Update Github Wiki following the convention
  .github/wiki/_Sidebar.md
Labels: type : chore
