Repository nimblehq/ios-templates, pull requests merged in 2023-11, with the labels that each got.

#538 [#509] Minimum ios version does not match the set version when create project with template
  Tuist/Interfaces/SwiftUI/Project/Podfile
  Tuist/Interfaces/UIKit/Project/Podfile
Labels: type : feature, good first issue

#533 [#522] Replace Firebase Token with Google Service Account
  .github/project_workflows/deploy_production_firebase.yml
  .github/project_workflows/deploy_staging_firebase.yml
  .github/wiki/CodeMagic.md
  .github/wiki/Github-Actions.md
  .github/workflows/test_upload_build_to_firebase.yml
  codemagic.yaml
  fastlane/Constants/Secret.swift
  fastlane/Helpers/Distribution.swift
Labels: type : feature

#539 [#521] [Chore] Update SwiftLint in GitHub Workflows to the newest version
  .github/project_workflows/deploy_app_store.yml
  .github/project_workflows/deploy_production_firebase.yml
  .github/project_workflows/deploy_staging_firebase.yml
Labels: type : chore, good first issue
