Repository nimblehq/ios-templates, pull requests merged in 2023-07, with the labels that each got.

#487 Release - 4.6.0
  .arkana.yml
  .env.example
  .github/workflows/automatic_pull_request_review.yml
  .github/workflows/deploy_app_store.yml
  .github/workflows/deploy_production_firebase.yml
  .github/workflows/deploy_staging_firebase.yml
  .github/workflows/test_install_script.yml
  .gitignore
  Gemfile
  Podfile
  make.sh
  {PROJECT_NAME}/Sources/Constants/Constants+API.swift
Labels: type : release

#486 [#483] Add SwiftUI Option to the Template
  .github/wiki/Deliverable-Configurations.md
  .github/wiki/Selecting-User-Interface.md
  .github/wiki/_Sidebar.md
  .github/workflows/test_install_script.yml
  .github/workflows/test_upload_build_to_firebase.yml
  .github/workflows/test_upload_build_to_test_flight.yml
  Scripts/Swift/Extensions/FileManager+Utils.swift
  Scripts/Swift/SetUpInterface.swift
  Tuist/Interfaces/SwiftUI/Project/.sourcery.yml
  Tuist/Interfaces/SwiftUI/Project/Podfile
  Tuist/Interfaces/SwiftUI/Sources/Application/App.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Models/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/NetworkAPI.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Data/Repositories/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Modules/HomeView.swift
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Views/.gitkeep
  Tuist/Interfaces/UIKit/Project/.sourcery.yml
  Tuist/Interfaces/UIKit/Project/Podfile
  Tuist/Interfaces/UIKit/Sources/Application/AppDelegate.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Models/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/NetworkAPI.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/Repositories/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Presentation/Modules/HomeViewController.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Navigator/Navigator+Scene.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Navigator/Navigator+Transition.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Navigator/Navigator.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Views/.gitkeep
  make.sh
  set_up_deliverable.sh
Labels: type : feature

#489 [#484] Add Build Test for SwiftUI Project
  .github/workflows/test_swiftui_install_script.yml
  .github/workflows/test_uikit_install_script.yml
Labels: type : chore

#496 [#490] Migrate `set_up_deliverable.sh` to Swift command
  .github/wiki/Deliverable-Configurations.md
  Scripts/Swift/Helpers/SafeShell.swift
  Scripts/Swift/SetUpCICDService.swift
  Scripts/Swift/SetUpDeliveryConstants.swift
  make.sh
  set_up_deliverable.sh
Labels: type : chore

#501 [#500] Update the SwiftUI project's structure
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Coordinators/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Models/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Styles/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/ViewIds/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/ViewModifiers/.gitkeep
Labels: type : feature
