Repository nimblehq/ios-templates, pull requests merged in 2023-02, with the labels that each got.

#436 Release - 4.1.0
  .github/wiki/Fastlane.md
  .github/wiki/assets/images/infrastructure/fastlane/fastlane.png
  .github/workflows/deploy_production_firebase.yml
  .github/workflows/deploy_staging_firebase.yml
Labels: type : release

#440 [#432] [Bug] Fix: DeliverableConstants.rb does not exist
  deliverable_setup.sh
Labels: type : bug

#441 [#438] [Bug] Fix: Remove Workspace.swift when make.sh success
  make.sh
Labels: type : bug

#442 [#433] [Bug] Fix: Lint and add SwiftFormat ignore to Fastlane Swift
  .swiftformat
  Workspace.swift
  fastlane/Appfile.swift
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Build.swift
  fastlane/Helpers/Version.swift
Labels: type : bug

#429 [#315] CI/CD - Add support for Codemagic CI/CD service
  .github/wiki/CodeMagic.md
  .github/wiki/_Sidebar.md
  Dangerfile
  codemagic.yaml
  deliverable_setup.sh
  fastlane/Constants/Constant.swift
  fastlane/Helpers/Build.swift
Labels: type : feature

#447 [#446] [Chore] Update the Pull Request Template to the latest version
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type : chore
