Repository nimblehq/ios-templates, pull requests merged in 2023-10, with the labels that each got.

#514 [#495] Package all Swift Commands
  .github/project_workflows/automatic_pull_request_review.yml
  .github/project_workflows/deploy_app_store.yml
  .github/project_workflows/deploy_production_firebase.yml
  .github/project_workflows/deploy_staging_firebase.yml
  .github/project_workflows/draft_a_new_release.yml
  .github/project_workflows/publish_docs_to_wiki.yml
  .github/wiki/Deliverable-Configurations.md
  .github/wiki/Getting-Started.md
  .github/wiki/Selecting-User-Interface.md
  .github/workflows/test_swiftui_install_script.yml
  .github/workflows/test_uikit_install_script.yml
  .github/workflows/test_upload_build_to_firebase.yml
  .github/workflows/test_upload_build_to_test_flight.yml
  .gitignore
  README.md
  Scripts/Swift/SetUpTestFirebase.swift
  Scripts/Swift/SetUpTestTestFlight.swift
  Scripts/Swift/iOSTemplateMaker/Package.resolved
  Scripts/Swift/iOSTemplateMaker/Package.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/Extensions/FileManager+Utils.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/Extensions/Optional+Utils.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/Extensions/String+Utils.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/Helpers/EnvironmentValue.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/Helpers/SafeShell.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/Models/EnvironmentKey.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpCICDService.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpDeliveryConstants.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpInterface.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpTestFirebase.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpTestTestFlight.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpiOSProject.swift
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/iOSTemplateMaker.swift
  Scripts/Swift/iOSTemplateMaker/Tests/iOSTemplateMakerTests/.gitkeep
  make.sh
Labels: type : chore

#525 [#515] Remove all Rx things
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  Tuist/Interfaces/UIKit/Project/Podfile
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Models/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/NetworkAPI.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  {PROJECT_NAME}/Sources/Data/NetworkAPI/Models/.gitkeep
  {PROJECT_NAME}/Sources/Data/NetworkAPI/NetworkAPI.swift
  {PROJECT_NAME}/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  {PROJECT_NAME}/Sources/Data/Repositories/.gitkeep
Labels: type : chore

#527 [#482] Migrate Quick/Nimble tests to Quick 7
  Tuist/Interfaces/SwiftUI/Project/Podfile
  Tuist/Interfaces/UIKit/Project/Podfile
  {PROJECT_NAME}KIFUITests/Sources/Specs/Application/ApplicationSpec.swift
  {PROJECT_NAME}KIFUITests/Sources/Utilities/KIF+Swift.swift
  {PROJECT_NAME}KIFUITests/Sources/Utilities/KIFSpec.swift
  {PROJECT_NAME}Tests/Sources/Specs/Data/NetworkAPI/NetworkAPISpec.swift
  {PROJECT_NAME}Tests/Sources/Specs/Supports/Extensions/Foundation/OptionalUnwrapSpec.swift
Labels: type : feature

#537 [#487] Update swiftlint implicit_return rule
  .swiftlint.yml
Labels: type : feature, good first issue

#529 [#528] Update Default timeout for Keychain to `no time-out`
  fastlane/Helpers/Keychain.swift
Labels: type : chore
