Repository nimblehq/ios-templates, pull requests merged in 2023-03, with the labels that each got.

#448 Release - 4.2.0
  .github/PULL_REQUEST_TEMPLATE.md
  .github/wiki/CodeMagic.md
  .github/wiki/_Sidebar.md
  .swiftformat
  Dangerfile
  Workspace.swift
  codemagic.yaml
  deliverable_setup.sh
  fastlane/Appfile.swift
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Build.swift
  fastlane/Helpers/Version.swift
  make.sh
Labels: type : release

#449 [Chore] Update Pods dependencies
  Podfile
Labels: type : chore

#452 [#430] Update Xcode build formatter from xcpretty to xcbeautify for buildApp and scan actions
  Podfile
  fastlane/Helpers/Build.swift
  fastlane/Helpers/Test.swift
Labels: type : chore

#461 [#460] [Chore] Replace cancel-workflow-action to Github Action's concurrency
  .github/workflows/automatic_pull_request_review.yml
  .github/workflows/deploy_app_store.yml
  .github/workflows/deploy_production_firebase.yml
  .github/workflows/deploy_staging_firebase.yml
  .github/workflows/test_install_script.yml
  .github/workflows/test_upload_build_to_test_flight.yml
Labels: type : chore

#426 [#425] As a developer, I would like to have KIF setup when I start a new project
  .github/wiki/Project-Configurations.md
  .github/wiki/Standard-File-Organization.md
  .swiftlint.yml
  Podfile
  Project.swift
  Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  make.sh
  {PROJECT_NAME}KIFUITests/Configurations/Plists/Info.plist
  {PROJECT_NAME}KIFUITests/Sources/Specs/Application/ApplicationSpec.swift
  {PROJECT_NAME}KIFUITests/Sources/Utilities/KIF+Swift.swift
  {PROJECT_NAME}Tests/Sources/Specs/Supports/Extensions/Foundation/OptionalUnwrapSpec.swift
  {PROJECT_NAME}UITests/Resources/.gitkeep
  {PROJECT_NAME}UITests/Sources/Specs/Application/ApplicationSpec.swift
Labels: type : feature

#464 Release - 4.3.0
  .github/wiki/Project-Configurations.md
  .github/wiki/Standard-File-Organization.md
  .github/workflows/automatic_pull_request_review.yml
  .github/workflows/deploy_app_store.yml
  .github/workflows/deploy_production_firebase.yml
  .github/workflows/deploy_staging_firebase.yml
  .github/workflows/test_install_script.yml
  .github/workflows/test_upload_build_to_test_flight.yml
  .swiftlint.yml
  Podfile
  Project.swift
  Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Build.swift
  fastlane/Helpers/Test.swift
  make.sh
  {PROJECT_NAME}KIFUITests/Configurations/Plists/Info.plist
  {PROJECT_NAME}KIFUITests/Sources/Specs/Application/ApplicationSpec.swift
  {PROJECT_NAME}KIFUITests/Sources/Utilities/KIF+Swift.swift
  {PROJECT_NAME}Tests/Sources/Specs/Supports/Extensions/Foundation/OptionalUnwrapSpec.swift
  {PROJECT_NAME}UITests/Resources/.gitkeep
  {PROJECT_NAME}UITests/Sources/Specs/Application/ApplicationSpec.swift
Labels: type : release
