Repository nimblehq/ios-templates, pull requests merged in 2023-01, with the labels that each got.

#417 [#390] [Chore] Merge develop to migrate-develop
  .github/release-drafter.yml
  .github/workflows/deploy_AppStore.yml
  .github/workflows/deploy_Firebase.yml
  .github/workflows/deploy_Release_Firebase.yml
  .github/workflows/draft-a-new-release.yml
  .swiftlint.yml
  Project.swift
  README.md
  bitrise.yml
  fastlane/Managers/EnvironmentManager.rb
Labels: type : chore

#413 [#399] [Bug] Fastlane Swift - Fix Cannot load such file -- ./fastlane/Constants/Constants
  .github/workflows/automatic_pull_request_review.yml
  Dangerfile
Labels: type : bug

#418 [#388] [Fastlane Swift] Rename FastlaneRunner Build Phase to mitigate risk of failing
  fastlane/swift/DeliverfileProtocol.swift
  fastlane/swift/Fastlane.swift
  fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj
  fastlane/swift/GymfileProtocol.swift
  fastlane/swift/MatchfileProtocol.swift
  fastlane/swift/PrecheckfileProtocol.swift
  fastlane/swift/ScanfileProtocol.swift
  fastlane/swift/ScreengrabfileProtocol.swift
  fastlane/swift/SnapshotfileProtocol.swift
Labels: type : feature, good first issue, fastlane swift

#420 [#405] [Chore] Refactor workflow yml files to snake_case naming convention
  .github/workflows/deploy_app_store.yml
  .github/workflows/draft_a_new_release.yml
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/test_install_script.yml
  .github/workflows/test_upload_build_to_test_flight.yml
Labels: type : chore

#424 [#422] [Chore] [Wiki] Update the Fastlane page
  .github/wiki/Fastlane.md
  .github/wiki/assets/images/infrastructure/fastlane/fastlane.png
Labels: type : chore

#428 [Chore] [#423] Update a specific name for deploying staging build to firebase workflow
  .github/workflows/deploy_production_firebase.yml
  .github/workflows/deploy_staging_firebase.yml
Labels: type : chore
