Repository nimblehq/ios-templates, pull requests merged in 2023-08, with the labels that each got.

#506 [#505] Set up necessary library for a SwiftUI project
  Tuist/Interfaces/SwiftUI/Project/Podfile
Labels: type : feature

#497 [#491] Migrate `set_up_test_firebase.sh` to Swift command
  .github/workflows/test_upload_build_to_firebase.yml
  Dangerfile
  Scripts/Swift/Extensions/FileManager+Utils.swift
  Scripts/Swift/SetUpCICDService.swift
  Scripts/Swift/SetUpTestFirebase.swift
  make.sh
  set_up_test_firebase.sh
Labels: type : chore

#511 Release - 4.7.0
  .github/wiki/Deliverable-Configurations.md
  .github/wiki/Selecting-User-Interface.md
  .github/wiki/_Sidebar.md
  .github/workflows/test_swiftui_install_script.yml
  .github/workflows/test_uikit_install_script.yml
  .github/workflows/test_upload_build_to_firebase.yml
  .github/workflows/test_upload_build_to_test_flight.yml
  Dangerfile
  Scripts/Swift/Extensions/FileManager+Utils.swift
  Scripts/Swift/Helpers/SafeShell.swift
  Scripts/Swift/SetUpCICDService.swift
  Scripts/Swift/SetUpDeliveryConstants.swift
  Scripts/Swift/SetUpInterface.swift
  Scripts/Swift/SetUpTestFirebase.swift
  Tuist/Interfaces/SwiftUI/Project/.sourcery.yml
  Tuist/Interfaces/SwiftUI/Project/Podfile
  Tuist/Interfaces/SwiftUI/Sources/Application/App.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/Models/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/NetworkAPI.swift
  Tuist/Interfaces/SwiftUI/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Data/Repositories/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Coordinators/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Models/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Modules/HomeView.swift
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Styles/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/ViewIds/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/ViewModifiers/.gitkeep
  Tuist/Interfaces/SwiftUI/Sources/Presentation/Views/.gitkeep
  Tuist/Interfaces/UIKit/Project/.sourcery.yml
  Tuist/Interfaces/UIKit/Project/Podfile
  Tuist/Interfaces/UIKit/Sources/Application/AppDelegate.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Interceptors/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/Models/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/NetworkAPI.swift
  Tuist/Interfaces/UIKit/Sources/Data/NetworkAPI/RequestConfigurations/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Data/Repositories/.gitkeep
  Tuist/Interfaces/UIKit/Sources/Presentation/Modules/HomeViewController.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Navigator/Navigator+Scene.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Navigator/Navigator+Transition.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Navigator/Navigator.swift
  Tuist/Interfaces/UIKit/Sources/Presentation/Views/.gitkeep
  deliverable_setup.sh
  make.sh
  set_up_test_firebase.sh
Labels: type : release

#512 [#492] Migrate set_up_test_testflight.sh to Swift command
  .github/workflows/test_upload_build_to_test_flight.yml
  Scripts/Swift/SetUpTestTestFlight.swift
  set_up_test_testflight.sh
Labels: type : chore

#513 [#510] GitHub actions can remove custom keychain when needed
  .github/workflows/deploy_app_store.yml
  .github/workflows/deploy_production_firebase.yml
  .github/workflows/deploy_staging_firebase.yml
  .github/workflows/test_upload_build_to_firebase.yml
  .github/workflows/test_upload_build_to_test_flight.yml
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Keychain.swift
  make.sh
Labels: type : feature
