Repository nimblehq/ios-templates, pull requests merged in 2023-12, with the labels that each got.

#544 [#519] Fix: Test run failed for not finding host application for staging scheme
  {PROJECT_NAME}/Configurations/Plists/Info.plist
  {PROJECT_NAME}/Configurations/XCConfigs/DebugProduction.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/DebugStaging.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/ReleaseProduction.xcconfig
  {PROJECT_NAME}/Configurations/XCConfigs/ReleaseStaging.xcconfig
Labels: type : bug

#549 [#548] [Chore] Fix lints after generating project
  .swiftformat
  .swiftlint.yml
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Keychain.swift
  fastlane/Helpers/Match.swift
  {PROJECT_NAME}KIFUITests/Sources/Utilities/KIF+Swift.swift
  {PROJECT_NAME}Tests/Sources/Specs/Data/NetworkAPI/NetworkAPISpec.swift
Labels: type : chore

#536 [#349] Add the domain and data layers as targets (modules) in the project
  Modules/Data/Sources/NetworkAPI/Core/NetworkAPIError.swift
  Modules/Data/Sources/NetworkAPI/Core/NetworkAPIProtocol.swift
  Modules/Data/Sources/NetworkAPI/Core/RequestConfiguration.swift
  Modules/Data/Sources/NetworkAPI/Interceptors/.gitkeep
  Modules/Data/Sources/NetworkAPI/Models/.gitkeep
  Modules/Data/Sources/NetworkAPI/NetworkAPI.swift
  Modules/Data/Sources/NetworkAPI/RequestConfigurations/.gitkeep
  Modules/Data/Sources/Repositories/.gitkeep
  Modules/Data/Tests/Resources/.gitkeep
  Modules/Data/Tests/Sources/Dummies/DummyNetworkModel.swift
  Modules/Data/Tests/Sources/Dummies/DummyRequestConfiguration.swift
  Modules/Data/Tests/Sources/Specs/NetworkAPI/NetworkAPISpec.swift
  Modules/Data/Tests/Sources/Utilities/NetworkStubber.swift
  Modules/Domain/Sources/Entities/.gitkeep
  Modules/Domain/Sources/Interfaces/.gitkeep
  Modules/Domain/Sources/UseCases/UseCaseFactoryProtocol.swift
  Modules/Domain/Tests/Resources/.gitkeep
  Modules/Domain/Tests/Sources/Specs/DummySpec.swift
  Project.swift
  Tuist/Interfaces/SwiftUI/Project/Podfile
  Tuist/Interfaces/UIKit/Project/Podfile
  Tuist/ProjectDescriptionHelpers/Constant.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift
  Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
  fastlane/Constants/Constant.swift
  fastlane/Fastfile.swift
  fastlane/Helpers/Test.swift
Labels: type : feature

#545 [#541] Update the iOS template project structure to reflect the new modules
  .github/wiki/Standard-File-Organization.md
Labels: type : content

#543 [#498] Add option: github-self-hosted while generating the project
  .github/self_hosted_project_workflows/automatic_pull_request_review.yml
  .github/self_hosted_project_workflows/deploy_app_store.yml
  .github/self_hosted_project_workflows/deploy_production_firebase.yml
  .github/self_hosted_project_workflows/deploy_staging_firebase.yml
  .github/self_hosted_project_workflows/draft_a_new_release.yml
  .github/self_hosted_project_workflows/publish_docs_to_wiki.yml
  Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpCICDService.swift
Labels: type : feature
